all:
	wget http://archive.ics.uci.edu/ml/machine-learning-databases/solar-flare/flare.data1
	wget http://archive.ics.uci.edu/ml/machine-learning-databases/solar-flare/flare.data2
	wget http://archive.ics.uci.edu/ml/machine-learning-databases/solar-flare/flare.names
	wget http://archive.ics.uci.edu/ml/machine-learning-databases/solar-flare/past-usage
clean:
	rm -f flare.data1 flare.data2 flare.names past-usage
