all:
	$(MAKE) -C annealing
	$(MAKE) -C power_consumption
	$(MAKE) -C solar_flares
	$(MAKE) -C twitter
	$(MAKE) -C housing
	$(MAKE) -C tic
	$(MAKE) -C auto_mpg
clean:
	$(MAKE) -C annealing clean
	$(MAKE) -C power_consumption clean
	$(MAKE) -C solar_flares clean
	$(MAKE) -C twitter clean
	$(MAKE) -C housing clean
	$(MAKE) -C tic clean
	$(MAKE) -C auto_mpg clean
