all:
	$(MAKE) -C annealing
	$(MAKE) -C power_consumption
	$(MAKE) -C solar_flares
	$(MAKE) -C twitter
clean:
	$(MAKE) -C annealing clean
	$(MAKE) -C power_consumption clean
	$(MAKE) -C solar_flares clean
	$(MAKE) -C twitter clean
