all:
	wget http://archive.ics.uci.edu/ml/machine-learning-databases/annealing/anneal.data
	wget http://archive.ics.uci.edu/ml/machine-learning-databases/annealing/anneal.names
	wget http://archive.ics.uci.edu/ml/machine-learning-databases/annealing/anneal.test
clean:
	rm -f anneal.data anneal.names anneal.test
