all:
	wget -nc http://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary/breast-cancer_scale
	wget -nc http://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary/heart_scale
	wget -nc http://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/multiclass/connect-4
	wget -nc http://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/multiclass/vehicle.scale
	wget -nc http://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/multiclass/vowel.scale
clean:
	rm -f breast-cancer_scale \
		  connect-4 \
		  gisette_scale \
		  heart_scale \
		  vehicle.scale \
		  vowel.scale
