all:
	wget http://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.names
	wget http://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data
clean:
	rm -f housing.names housing.data
