all:
	wget http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data
	wget http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data-original
	wget http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.names
clean:
	rm -f auto-mpg.data auto-mpg.data-original auto-mpg.names
