all:
	wget http://archive.ics.uci.edu/ml/machine-learning-databases/00235/household_power_consumption.zip
	unzip household_power_consumption.zip
clean:
	rm -f household_power_consumption.zip household_power_consumption.txt
